batch_size: 64
base_dir_eval: runs/homology_only/eval

lambda_hier: 0.001
pos_weight_cap: 10.0

use_wandb: True
wandb_project: seq_homology_reliability-aware-pfp
wandb_entity:
wandb_mode: offline
